-- Clean slate
DROP DATABASE IF EXISTS :"DB_NAME";
DROP ROLE IF EXISTS :"DB_USER";

-- User for PromptDev
CREATE ROLE :"DB_USER" LOGIN PASSWORD :'DB_PASS';

-- Database for PromptDev
CREATE DATABASE :"DB_NAME" OWNER :"DB_USER";

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE :"DB_NAME" TO :"DB_USER";
